package com.harte.meteireannwidget.met;

public enum County {
        Antrim,
        Armagh,
        Carlow,
        Cavan,
        Clare,
        Cork,
        Derry,
        Donegal,
        Down,
        Dublin,
        Fermanagh,
        Galway,
        Kerry,
        Kildare,
        Kilkenny,
        Laois,
        Leitrim,
        Limerick,
        Longford,
        Louth,
        Mayo,
        Meath,
        Monaghan,
        Offaly,
        Roscommon,
        Sligo,
        Tipperary,
        Tyrone,
        Waterford,
        Westmeath,
        Wexford,
        Wicklow
    }
